POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "Nukkuminen normaaliasennossa",
    "author": "Jussi Tiiri",
    "url": "error500.fi",
    "likes": 0
}

###

POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "JussinUusiTili",
    "name": "Jussi Tiiri",
    "password": "turvaton_salasana"
}