POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikp1c3NpblV1c2lUaWxpIiwiaWQiOiI2YTY4ODY0NTVmZjUxZDhlNDcxNGI0ODEiLCJpYXQiOjE3ODUyMzYxMDN9.Of8XTmumoqujb2HXCYHHAguRFHpSzXWNUSvXkWFL6qc

{
    "title": "Voinko lopettaa blogien kirjoittamisen ?!!",
    "author": "Jussi Tiiri",
    "url": "error500.fi",
    "likes": 0
}

###

POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "JussinUusiTili",
    "name": "Jussi Tiiri",
    "password": "turvaton_salasana"
}

###

POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "JussinUusiTili",
    "password": "turvaton_salasana"
}